name: deploy-container

on:
  push:
    branches:
      - main
    # paths:
    #   - 'container/**'

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: npm install package
        run: npm install

      - name: npm build package
        run: npm run build

      - name: aws version
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/ubuntu-latest 

      # - uses: chrislennon/action-aws-cli@v1.1
      # - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/ubuntu-latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: ap-southeast-1

